# @package _global_
core_lib:
  tack_core_lib:
    cache:
      track:
        type: memcached
        url:
          host: ${oc.env:MEMCACHED_HOST}
          port: ${oc.env:MEMCACHED_PORT}
  data:
    sqlalchemy:
      log_queries: false
      create_db: true
      url:
        protocol: sqlite
        file: track.db
